# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
#- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Building an image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        command: Build an image
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: products-service
        tags: |
          $(tag)
