# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

##########################################################
# Realizamos an치lisis de c칩digo est치tico con SonarCloud
##########################################################
- task: SonarCloudPrepare@1
  displayName: Configurar SonarCloud
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'devops-ort-g2'
    scannerMode: 'Other'

- script: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DevOps-ORT-G2_products-service
  displayName: 'Ejecutar an치lisis de SonarCloud'

- task: SonarCloudPublish@1
  displayName: Publicar resultado en el resultado del pipeline
  inputs:
    pollingTimeoutSec: '300'



##########################################################
# AGREGAR CONTROL DE FAIL PARA SONARCLOUD
##########################################################



##########################################################
# Buildeamos el JAR
##########################################################

- script: mvn install
  displayName: Generar build del jar
    



##########################################################
# Buildeamos imagen docker
##########################################################
- task: Docker@1
  displayName: Realizar build de imagen docker
  inputs:
    command: 'Build an image'
    dockerFile: '**/Dockerfile'
    arguments: '--build-arg JAR_FILE=target/products-service-example-0.0.1-SNAPSHOT.jar'
    imageName: 'products-service'

- task: Docker@2
  displayName: Levantar docker 
  inputs:
    command: 'run'
    arguments: '-d --name products-service-test products-service'
    addPipelineData: false
    addBaseImageData: false

#- script: docker run -d --name products-service-test products-service
#  displayName: levanto docker  manual

- script: docker ps -a
  displayName: hay docker levantado?
    
##########################################################
# Pusheamos la imagen de docker al ECR
##########################################################
#- task: ECRPushImage@1
#  inputs:
#    awsCredentials: 'AWS'
#    regionName: 'us-east-1'
#    imageSource: 'imagename'
#    sourceImageName: 'products-service'
#    repositoryName: 'products-service'
    